@port = 3000

# =================================================================================================
#  GENERAL SERVER API                                                                                          
# =================================================================================================

###
GET http://localhost:{{port}}/

### Check server runtime
GET http://localhost:{{port}}/server-runtime


# =================================================================================================
#  GET RUN BY ID                                                                                        
# =================================================================================================

### correct ID #1
GET http://localhost:{{port}}/runs/dc9822e7-72d6-4cc8-b6da-c1c5208d6109

### correct ID #2
GET http://localhost:{{port}}/runs/0a08a75c-e72d-4b7b-bf77-be9bd105b68d

### incorrect ID #1
GET http://localhost:{{port}}/runs/0a08a83c-e72d-4b7b-bf77-bc9bd225b68d

### incorrect ID #2 (wrong format)
GET http://localhost:{{port}}/runs/000000zdg000000000000000000

# =================================================================================================
#  POST NEW DATA IN                                                                                        
# ===========================================================================================

### Good entry
POST http://localhost:3000/runs/
Content-Type: application/json

{
  "userId": "1d9a8400-07cd-466a-9d13-843a544a5b09",
  "startTime": "2026-01-19T12:25:44.822Z",
  "durationSec": 457,
  "distanceMeters": 1574
}


### Wrong type
POST http://localhost:3000/runs/


### Empty JSON
POST http://localhost:3000/runs/
Content-Type: application/json

{

}

### Missing duration
POST http://localhost:3000/runs/
Content-Type: application/json

{
  "userId": "1d9a8400-07cd-466a-9d13-843a544a5b09",
  "startTime": "2026-01-11T14:45:44.822Z",
  "distanceMeters": 1727
}


### Bad JSON
POST http://localhost:3000/runs/
Content-Type: application/json

{
  "userId": "1d9a8400-07cd-466a-9d13-843a544a5b09",
  "startTime": "2026-01-11T14:45:44.822Z",
  "durationSec": 1550da,
  "distanceMeters": 1727
}


### Bad userId
POST http://localhost:3000/runs/
Content-Type: application/json

{
  "userId": "fagfgsg5054a6wa6ew1",
  "startTime": "2026-01-11T14:45:44.822Z",
  "durationSec": 1550,
  "distanceMeters": 1727
}


### Bad date
POST http://localhost:3000/runs/
Content-Type: application/json

{
  "userId": "1d9a8400-07cd-466a-9d13-843a544a5b09",
  "startTime": "2026-31-11T14:45:44.822Z",
  "durationSec": 1550,
  "distanceMeters": 1727
}

### Bad date
POST http://localhost:3000/runs/
Content-Type: application/json

{
  "userId": "1d9a8400-07cd-466a-9d13-843a544a5b09",
  "startTime": 123456,
  "durationSec": 1550,
  "distanceMeters": 1727
}


### Bad duration
POST http://localhost:3000/runs/
Content-Type: application/json

{
  "userId": "1d9a8400-07cd-466a-9d13-843a544a5b09",
  "startTime": "2026-01-11T14:45:44.822Z",
  "durationSec": "-1455a",
  "distanceMeters": 1727
}


### Bad distance
POST http://localhost:3000/runs/
Content-Type: application/json

{
  "userId": "1d9a8400-07cd-466a-9d13-843a544a5b09",
  "startTime": "2026-01-11T14:45:44.822Z",
  "durationSec": 1727,
  "distanceMeters": "-1455a"
}

### Good new user data
POST http://localhost:3000/users/
Content-Type: application/json

{
  "username": "fastfeet",
  "password": "StrongPassword!123",
  "email": "runner@example.com"
}



### Good Login
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "fastfeet",
  "password": "StrongPassword!123",
  "email": "runner@example.com"
}


### Bad Login
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "fastfeet",
  "password": "WrongPassword!456",
  "email": "runner@example.com"
}


### No authorization header.
GET http://localhost:3000/users/01ddb911-549f-4b59-8de3-41402bf4789f
Content-Type: application/json

### Bad header.
GET http://localhost:3000/users/01ddb911-549f-4b59-8de3-41402bf4789f
Authorization: blabla

### Bad header.
GET http://localhost:3000/users/01ddb911-549f-4b59-8de3-41402bf4789f
Authorization: Bearer 41

### Expired token.
GET http://localhost:3000/users/01ddb911-549f-4b59-8de3-41402bf4789fe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxOTg4ZjRiMS00MGZmLTQxNmQtOWI1MS1iYjI0Nzk3YWQyNDIiLCJ1c2VybmFtZSI6ImZhc3RmZWV0IiwiZW1haWwiOiJydW5uZXJAZXhhbXBsZS5jb20iLCJpYXQiOjE3Njk0Mjg2NzAsImV4cCI6MTc2OTQzMjI3MCwiaXNzIjoicnVubmVycy1hcGkifQ.YiVBnh5eRCyJstyuofQ3kVKnaI0nwn8SXjXAuxTKa-c


### good token.
GET http://localhost:3000/users/01ddb911-549f-4b59-8de3-41402bf4789f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMWRkYjkxMS01NDlmLTRiNTktOGRlMy00MTQwMmJmNDc4OWYiLCJpYXQiOjE3Njk0MzkwNjUsImV4cCI6MTc2OTQ0MjY2NSwiaXNzIjoicnVubmVycy1hcGkifQ.EYixoy_l6tryesBE2cMT04itxzB8FtQTECQfpidJsIA


### good token, wrong id.
GET http://localhost:3000/users/8e468a42-b31d-4893-974a-f71a1187b09a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMWRkYjkxMS01NDlmLTRiNTktOGRlMy00MTQwMmJmNDc4OWYiLCJpYXQiOjE3Njk0MzkwNjUsImV4cCI6MTc2OTQ0MjY2NSwiaXNzIjoicnVubmVycy1hcGkifQ.EYixoy_l6tryesBE2cMT04itxzB8FtQTECQfpidJsIA


### Ilo

POST http://172.18.19.93:3003/api/topics
Content-Type: application/json

{
  "title": "[not today] Deploying api server on cloud service."
}